FROM node:18-alpine

WORKDIR /app

COPY package*.json tsconfig.json ./
RUN npm install

COPY . .

EXPOSE 5000

CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "--poll", "--watch", "src", "src/server.ts"]