services:
  server:
    build:
      context: .
      dockerfile: dockerfile.dev
      args:
        NODE_ENV: development
    container_name: twincredits-server-dev
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install &&
             npx ts-node-dev --respawn --transpile-only --poll --debug --watch src src/server.ts"
    restart: unless-stopped